services:
  - type: web
    name: crime-awareness-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
<<<<<<< HEAD
        sync: false
=======
        sync: false
>>>>>>> 99548e130a923a9864ad0e8fcb481a2110430117
